apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: batch-web
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: batch-web
spec:
  env:
  - name: SPRING_DATASOURCE_DRIVERCLASSNAME
    value: org.postgresql.Driver
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/making/batch-web
      ref:
        branch: main
  serviceClaims:
  - name: job-db
    ref:
      apiVersion: sql.tanzu.vmware.com/v1
      kind: Postgres
      name: job-db